# All the variables should be queried from .env file
log_level: "DEBUG"
app:
  secret_key: !ENV ${SECRET_KEY}
  history_path: "static/history"
  host: "0.0.0.0"
  port: "5000"
google:
  client_id: !ENV ${GOOGLE_CLIENT_ID}
  client_secret: !ENV ${GOOGLE_CLIENT_SECRET}
  authorization_base_url: "https://accounts.google.com/o/oauth2/v2/auth"
  token_url: "https://www.googleapis.com/oauth2/v4/token"
  user_info_url: "https://www.googleapis.com/oauth2/v1/userinfo"
email:
  MAIL_SERVER: "smtp.googlemail.com"
  MAIL_PORT: "465"
  MAIL_USE_TLS: "False"
  MAIL_USE_SSL: "True"
  MAIL_USERNAME: !ENV ${APP_MAIL_USERNAME}
  MAIL_PASSWORD: !ENV ${APP_MAIL_PASSWORD}
  SECURITY_PASSWORD_SALT: !ENV ${SECURITY_PASSWORD_SALT}
  MAIL_DEFAULT_SENDER: "from@example.com"
database:
  user: !ENV ${MYSQL_USER}
  password: !ENV ${MYSQL_PASSWORD}
  host: !ENV ${MYSQL_HOST}
  database: !ENV ${MYSQL_DATABASE}
